const trendingTopicsConstants = {
  GET_TRENDING_TOPICS__REQUEST: 'GET_TRENDING_TOPICS__REQUEST',
  GET_TRENDING_TOPICS__SUCCESS: 'GET_TRENDING_TOPICS__SUCCESS',
  GET_TRENDING_TOPICS__FAILURE: 'GET_TRENDING_TOPICS__FAILURE'
};

export default trendingTopicsConstants;
