const webinarConstants = {
  GET_ALL_WEBINARS_REQUEST: 'GET_ALL_WEBINARS_REQUEST',
  GET_ALL_WEBINARS_SUCCESS: 'GET_ALL_WEBINARS_SUCCESS',
  GET_ALL_WEBINARS_FAILURE: 'GET_ALL_WEBINARS_FAILURE'
}

export default webinarConstants;
