const courseDetailsConstants = {
  GET_COURSE_DETAILS__REQUEST: 'GET_COURSE_DETAILS__REQUEST',
  GET_COURSE_DETAILS__SUCCESS: 'GET_COURSE_DETAILS__SUCCESS',
  GET_COURSE_DETAILS__FAILURE: 'GET_COURSE_DETAILS__FAILURE'
}

const homePageConstants = {
  GET_HOME_DETAILS__REQUEST: 'GET_HOME_DETAILS__REQUEST',
  GET_HOME_DETAILS__SUCCESS: 'GET_HOME_DETAILS__SUCCESS',
  GET_HOME_DETAILS__FAILURE: 'GET_HOME_DETAILS__FAILURE'
}

const allCoursesConstants = {
  GET_ALL_COURSES__REQUEST: 'GET_ALL_COURSES__REQUEST',
  GET_ALL_COURSES__SUCCESS: 'GET_ALL_COURSES__SUCCESS',
  GET_ALL_COURSES__FAILURE: 'GET_ALL_COURSES__FAILURE'
}

const searchConstants = {
  GET_SEARCH__REQUEST: 'GET_SEARCH__REQUEST',
  GET_SEARCH__SUCCESS: 'GET_SEARCH__SUCCESS',
  GET_SEARCH__FAILURE: 'GET_SEARCH__FAILURE'
}

const searchHintConstants = {
  GET_SEARCH_HINT__REQUEST: 'GET_SEARCH_HINT__REQUEST',
  GET_SEARCH_HINT__SUCCESS: 'GET_SEARCH_HINT__SUCCESS',
  GET_SEARCH_HINT__FAILURE: 'GET_SEARCH_HINT__FAILURE'
}

const categoryConstants = {
  GET_CATEGORY__REQUEST: 'GET_CATEGORY__REQUEST',
  GET_CATEGORY__SUCCESS: 'GET_CATEGORY__SUCCESS',
  GET_CATEGORY__FAILURE: 'GET_CATEGORY__FAILURE'
}

const getStartedConstants = {
  GET_GETSTARTED__REQUEST: 'GET_GETSTARTED__REQUEST',
  GET_GETSTARTED__SUCCESS: 'GET_GETSTARTED__SUCCESS',
  GET_GETSTARTED__FAILURE: 'GET_GETSTARTED__FAILURE'
}

const registerWebinarConstants = {
  GET_WEBINAR__REQUEST: 'GET_WEBINAR__REQUEST',
  GET_WEBINAR__SUCCESS: 'GET_WEBINAR__SUCCESS',
  GET_WEBINAR__FAILURE: 'GET_WEBINAR__FAILURE'
}

const reviewDetailsConstants = {
  GET_REVIEW_DETAILS__REQUEST: 'GET_REVIEW_DETAILS__REQUEST',
  GET_REVIEW_DETAILS__SUCCESS: 'GET_REVIEW_DETAILS__SUCCESS',
  GET_REVIEW_DETAILS__FAILURE: 'GET_REVIEW_DETAILS__FAILURE'
}
const orderSummaryConstants = {
  GET_ORDER_SUMMARY__REQUEST: 'GET_ORDER_SUMMARY__REQUEST',
  GET_ORDER_SUMMARY__SUCCESS: 'GET_ORDER_SUMMARY__SUCCESS',
  GET_ORDER_SUMMARY__FAILURE: 'GET_ORDER_SUMMARY__FAILURE'
}
const promoCodeConstants = {
  GET_PROMO_CODE_REQUEST: 'GET_PROMO_CODE_REQUEST',
  GET_PROMO_CODE_SUCCESS: 'GET_PROMO_CODE_SUCCESS',
  GET_PROMO_CODE_FAILURE: 'GET_PROMO_CODE_FAILURE',
  CLEAR_PROMO_CODE_INFO: 'CLEAR_PROMO_CODE_INFO'
}
const profileInfoConstants = {
  GET_PROFILE_INFO__REQUEST: 'GET_PROFILE_INFO__REQUEST',
  GET_PROFILE_INFO__SUCCESS: 'GET_PROFILE_INFO__SUCCESS',
  GET_PROFILE_INFO__FAILURE: 'GET_PROFILE_INFO__FAILURE'
}
const signinConstants = {
  GET_SIGN_DETAILS__REQUEST: 'GET_SIGN_DETAILS__REQUEST',
  GET_SIGN_DETAILS__SUCCESS: 'GET_SIGN_DETAILS__SUCCESS',
  GET_SIGN_DETAILS__FAILURE: 'GET_SIGN_DETAILS__FAILURE'
}
const signupConstants = {
  GET_SIGNUP_DETAILS__REQUEST: 'GET_SIGNUP_DETAILS__REQUEST',
  GET_SIGNUP_DETAILS__SUCCESS: 'GET_SIGNUP_DETAILS__SUCCESS',
  GET_SIGNUP_DETAILS__FAILURE: 'GET_SIGNUP_DETAILS__FAILURE'
}
const myCourseConstants = {
  GET_MYCOURSE_DETAILS__REQUEST: 'GET_MYCOURSE_DETAILS__REQUEST',
  GET_MYCOURSE_DETAILS__SUCCESS: 'GET_MYCOURSE_DETAILS__SUCCESS',
  GET_MYCOURSE_DETAILS__FAILURE: 'GET_MYCOURSE_DETAILS__FAILURE'
}
const myBatchesConstants = {
  GET_MYBATCHES__REQUEST: 'GET_MYBATCHES__REQUEST',
  GET_MYBATCHES__SUCCESS: 'GET_MYBATCHES__SUCCESS',
  GET_MYBATCHES__FAILURE: 'GET_MYBATCHES__FAILURE'
}
const groomingConstants = {
  UPDATE_GROOMING__REQUEST: 'UPDATE_GROOMING__REQUEST',
  UPDATE_GROOMING__SUCCESS: 'UPDATE_GROOMING__SUCCESS',
  UPDATE_GROOMING__FAILURE: 'UPDATE_GROOMING__FAILURE'
}
const relevatCoursesConstants = {
  GET_RELEVANT_COURSES__REQUEST: 'GET_RELEVANT_COURSES__REQUEST',
  GET_RELEVANT_COURSES__SUCCESS: 'GET_RELEVANT_COURSES__SUCCESS',
  GET_RELEVANT_COURSES__FAILURE: 'GET_RELEVANT_COURSES__FAILURE'
}
const LMSConstants = {
  GET_LMS_DETAILS__REQUEST: 'GET_LMS_DETAILS__REQUEST',
  GET_LMS_DETAILS__SUCCESS: 'GET_LMS_DETAILS__SUCCESS',
  GET_LMS_DETAILS__FAILURE: 'GET_LMS_DETAILS__FAILURE'
}

const LBayBatchDetailsConstants = {
  GET_LBAY_BATCH_DETAILS__REQUEST: 'GET_LBAY_BATCH_DETAILS__REQUEST',
  GET_LBAY_BATCH_DETAILS__SUCCESS: 'GET_LBAY_BATCH_DETAILS__SUCCESS',
  GET_LBAY_BATCH_DETAILS__FAILURE: 'GET_LBAY_BATCH_DETAILS__FAILURE'
}

const countryDdConstants = {
  GET_COUNTRIES__REQUEST: 'GET_COUNTRIES__REQUEST',
  GET_COUNTRIES__SUCCESS: 'GET_COUNTRIES__SUCCESS',
  GET_COUNTRIES__FAILURE: 'GET_COUNTRIES__FAILURE'
}

const contactPopupConstants = {
  GET_CONTACT__REQUEST: 'GET_CONTACT__REQUEST',
  GET_CONTACT__SUCCESS: 'GET_CONTACT__SUCCESS',
  GET_CONTACT__FAILURE: 'GET_CONTACT__FAILURE'
}

const otpConstants = {
  GET_OTP__REQUEST: 'GET_OTP__REQUEST',
  GET_OTP__SUCCESS: 'GET_OTP__SUCCESS',
  GET_OTP__FAILURE: 'GET_OTP__FAILURE'
}

const resetPassword = {
  GET_RESETPASSWORD__REQUEST: 'GET_RESETPASSWORD__REQUEST',
  GET_RESETPASSWORD__SUCCESS: 'GET_RESETPASSWORD__SUCCESS',
  GET_RESETPASSWORD__FAILURE: 'GET_RESETPASSWORD__FAILURE'
}

const newPassword = {
  GET_NEWPASSWORD__REQUEST: 'GET_NEWPASSWORD__REQUEST',
  GET_NEWPASSWORD__SUCCESS: 'GET_NEWPASSWORD__SUCCESS',
  GET_NEWPASSWORD__FAILURE: 'GET_NEWPASSWORD__FAILURE'
}

const courseList = {
  GET_COURSE_FIRST__REQUEST: 'GET_COURSE_FIRST__REQUEST',
  GET_COURSE_FIRST__SUCCESS: 'GET_COURSE_FIRST__SUCCESS',
  GET_COURSE_FIRST__FAILURE: 'GET_COURSE_FIRST__FAILURE'
}

const seoConstants = {
  GET_SEO__REQUEST: 'GET_SEO__REQUEST',
  GET_SEO__SUCCESS: 'GET_SEO__SUCCESS',
  GET_SEO__FAILURE: 'GET_SEO__FAILURE'
}

const offerConstants = {
  GET_OFFER__REQUEST: 'GET_OFFER__REQUEST',
  GET_OFFER__SUCCESS: 'GET_OFFER__SUCCESS',
  GET_OFFER__FAILURE: 'GET_OFFER__FAILURE'
}

const upcominConstants = {
  GET_UPCOMING__REQUEST: 'GET_UPCOMING__REQUEST',
  GET_UPCOMING__SUCCESS: 'GET_UPCOMING__SUCCESS',
  GET_UPCOMING__FAILURE: 'GET_UPCOMING__FAILURE'
}

const submitQuiz = {
  GET_QUIZ__REQUEST: 'GET_QUIZ__REQUEST',
  GET_QUIZ__SUCCESS: 'GET_QUIZ__SUCCESS',
  GET_QUIZ__FAILURE: 'GET_QUIZ__FAILURE'
}

const resendOtp = {
  GET_RESENDOTP__REQUEST: 'GET_RESENDOTP__REQUEST',
  GET_RESENDOTP__SUCCESS: 'GET_RESENDOTP__SUCCESS',
  GET_RESENDOTP__FAILURE: 'GET_RESENDOTP__FAILURE'
}

const affiliate = {
  GET_AFFILIATE__REQUEST: 'GET_AFFILIATE__REQUEST',
  GET_AFFILIATE__SUCCESS: 'GET_AFFILIATE__SUCCESS',
  GET_AFFILIATE__FAILURE: 'GET_AFFILIATE__FAILURE'
}

const changePassword = {
  GET_CHANGE__REQUEST: 'GET_CHANGE__REQUEST',
  GET_CHANGE__SUCCESS: 'GET_CHANGE__SUCCESS',
  GET_CHANGE__FAILURE: 'GET_CHANGE__FAILURE'
}

const classRecordings = {
  GET_RECORDINGS__REQUEST: 'GET_RECORDINGS__REQUEST',
  GET_RECORDINGS__SUCCESS: 'GET_RECORDINGS__SUCCESS',
  GET_RECORDINGS__FAILURE: 'GET_RECORDINGS__FAILURE'
}

const attendance = {
  GET_ATTENDANCE__REQUEST: 'GET_ATTENDANCE__REQUEST',
  GET_ATTENDANCE__SUCCESS: 'GET_ATTENDANCE__SUCCESS',
  GET_ATTENDANCE__FAILURE: 'GET_ATTENDANCE__FAILURE'
}

const requestCertificate = {
  GET_REQCERT__REQUEST: 'GET_REQCERT__REQUEST',
  GET_REQCERT__SUCCESS: 'GET_REQCERT__SUCCESS',
  GET_REQCERT__FAILURE: 'GET_REQCERT__FAILURE'
}

const myorders = {
  GET_MYORDERS__REQUEST: 'GET_MYORDERS__REQUEST',
  GET_MYORDERS__SUCCESS: 'GET_MYORDERS__SUCCESS',
  GET_MYORDERS__FAILURE: 'GET_MYORDERS__FAILURE'
}

const batchSelection = {
  GET_BATCHSELECTION__REQUEST: 'GET_BATCHSELECTION__REQUEST',
  GET_BATCHSELECTION__SUCCESS: 'GET_BATCHSELECTION__SUCCESS',
  GET_BATCHSELECTION__FAILURE: 'GET_BATCHSELECTION__FAILURE'
}

const requestCallback = {
  GET_CALLBACK__REQUEST: 'GET_CALLBACK__REQUEST',
  GET_CALLBACK__SUCCESS: 'GET_CALLBACK__SUCCESS',
  GET_CALLBACK__FAILURE: 'GET_CALLBACK__FAILURE'
}

const promoCode = {
  GET_PROMOCODE__REQUEST: 'GET_PROMOCODE__REQUEST',
  GET_PROMOCODE__SUCCESS: 'GET_PROMOCODE__SUCCESS',
  GET_PROMOCODE__FAILURE: 'GET_PROMOCODE__FAILURE'
}

const referal = {
  GET_REFERAL__REQUEST: 'GET_REFERAL__REQUEST',
  GET_REFERAL__SUCCESS: 'GET_REFERAL__SUCCESS',
  GET_REFERAL__FAILURE: 'GET_REFERAL__FAILURE'
}

const CRMleadCaptureConstants = {
  POST_LEAD_REQUEST: 'POST_LEAD_REQUEST',
  POST_LEAD_SUCCESS: 'POST_LEAD_SUCCESS',
  POST_LEAD_FAILURE: 'POST_LEAD_FAILURE'
}

const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const monthsHalf = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec']

export {
  courseDetailsConstants,
  homePageConstants,
  months,
  monthsHalf,
  reviewDetailsConstants,
  orderSummaryConstants,
  signinConstants,
  signupConstants,
  allCoursesConstants,
  searchConstants,
  categoryConstants,
  searchHintConstants,
  myCourseConstants,
  myBatchesConstants,
  groomingConstants,
  relevatCoursesConstants,
  LMSConstants,
  countryDdConstants,
  contactPopupConstants,
  courseList,
  offerConstants,
  seoConstants,
  otpConstants,
  resendOtp,
  upcominConstants,
  resetPassword,
  LBayBatchDetailsConstants,
  newPassword,
  getStartedConstants,
  registerWebinarConstants,
  requestCertificate,
  submitQuiz,
  affiliate,
  changePassword,
  profileInfoConstants,
  classRecordings,
  attendance,
  batchSelection,
  requestCallback,
  myorders,
  promoCode,
  referal,
  promoCodeConstants,
  CRMleadCaptureConstants
};
