const redeemWalletConstants = {
  GET_REDEEM_WALLET_REQUEST: 'GET_REDEEM_WALLET_REQUEST',
  GET_REDEEM_WALLET_SUCCESS: 'GET_REDEEM_WALLET_SUCCESS',
  GET_REDEEM_WALLET_FAILURE: 'GET_REDEEM_WALLET_FAILURE'
}

export default redeemWalletConstants;
