const batchInfoConstants = {
  GET_BATCH_INFO_REQUEST: 'GET_BATCH_INFO_REQUEST',
  GET_BATCH_INFO_SUCCESS: 'GET_BATCH_INFO_SUCCESS',
  GET_BATCH_INFO_FAILURE: 'GET_BATCH_INFO_FAILURE'
}

export default batchInfoConstants;
