const eventInfoConstants = {
  GET_EVENT_DETAILS_REQUEST: 'GET_EVENT_DETAILS_REQUEST',
  GET_EVENT_DETAILS_SUCCESS: 'GET_EVENT_DETAILS_SUCCESS',
  GET_EVENT_DETAILS_FAILURE: 'GET_EVENT_DETAILS_FAILURE'
}

export default eventInfoConstants;
