const reqBatchConstants = {
  POST_REQUEST_BATCH_REQUEST: 'POST_REQUEST_BATCH_REQUEST',
  POST_REQUEST_BATCH_SUCCESS: 'POST_REQUEST_BATCH_SUCCESS',
  POST_REQUEST_BATCH_FAILURE: 'POST_REQUEST_BATCH_FAILURE'
}

export default reqBatchConstants;
