const freeEnrollConstants = {
  POST_FREE_COURSE_ENROLL_REQUEST: 'POST_FREE_COURSE_ENROLL_REQUEST',
  POST_FREE_COURSE_ENROLL_SUCCESS: 'POST_FREE_COURSE_ENROLL_SUCCESS',
  POST_FREE_COURSE_ENROLL_FAILURE: 'POST_FREE_COURSE_ENROLL_FAILURE'
}

export default freeEnrollConstants;
