const userPrefConstants = {
  GET_USER_PREF_INFO_REQUEST: 'GET_USER_PREF_INFO_REQUEST',
  GET_USER_PREF_INFO_SUCCESS: 'GET_USER_PREF_INFO_SUCCESS',
  GET_USER_PREF_INFO_FAILURE: 'GET_USER_PREF_INFO_FAILURE',
  SET_USER_PREF_INFO_REQUEST: 'SET_USER_PREF_INFO_REQUEST',
  SET_USER_PREF_INFO_SUCCESS: 'SET_USER_PREF_INFO_SUCCESS',
  SET_USER_PREF_INFO_FAILURE: 'SET_USER_PREF_INFO_FAILURE',
  SET_USER_PREF_INFO_LOCAL: 'SET_USER_PREF_INFO_LOCAL'
}

export default userPrefConstants;
